# Define UI for application that draws a histogram
function(request){
    shinyUI(dashboardPage(title = "Cary",
        dashboardHeader(title = "Cary"),
        dashboardSidebar(collapsed = TRUE,
            sidebarMenu(id="sidebarmenu",
                menuItem("CAR SOM", tabName = "carsom", icon = icon("map"))
            )
        ),
        dashboardBody(
            useShinyjs(),
            extendShinyjs(text = "shinyjs.resetClick = function() { Shiny.onInputChange('plotly_click-carsomUmatrix2d', 'null'); }", functions = c("resetClick")),
            extendShinyjs(text = "shinyjs.resetBrushed = function() { Shiny.onInputChange('plotly_brushed-carsomUmatrix2d', 'null'); }", functions = c("resetBrushed")),
            tabItems(
                tabItem(tabName = "carsom",
                        fluidRow(
                            box(width=2,
                                textInput("searchTitleCar", "Search", placeholder="Regular Expression"),
                                # dateRangeInput("daterangeCar", "Date range", start = Sys.Date()-(365*70), end = Sys.Date()),
                                actionButton("runsearchQuery", "Search"),
                                selectInput("propertySelection", "Property", choices = "umatrix"),
                                actionButton("runQuery", "Query"),
                                numericInput("driven_km", "Driven km", 0, min=0),
                                numericInput("power_kW", "Power kW", 0, min=0),
                                numericInput("displacement_cc", "Displacement cc", 0, min=0),
                                numericInput("number_doors", "Number of doors", 4, min=2),
                                numericInput("number_seats", "Number of seats", 5, min=2),
                                numericInput("owner_count", "Number of owners", 1, min=0),
                                dateInput("registration", "Date of registration"),
                                numericInput("weight_kg", "Weight kg", 1000, min=500),
                                numericInput("consumption_comb", "Consumption Combi kg", 3, min=3),
                                numericInput("consumption_city", "Consumption City", 3, min=3),
                                numericInput("consumption_country", "Consumption Country", 3, min=3),
                                numericInput("co2_emission", "CO2 Emission", 100, min=0),
                                selectInput("drive_chain", "Drive Chain", c("4WD", "front", "rear")),
                                selectInput("gearing_type", "Gearing Type", c("Automatic", 
                                                                              "Manual", 
                                                                              "Semi Automatic")),
                                selectInput("emission", "Emission", c("Label 1 (No Sticker)", 
                                                                      "Label 2 (Red)", 
                                                                      "Label 3 (Yellow)",
                                                                      "Label 4 (Green)",
                                                                      "Label 5 (Blue)",
                                                                      "Euro 1",
                                                                      "Euro 2",
                                                                      "Euro 3",
                                                                      "Euro 4",
                                                                      "Euro 5",
                                                                      "Euro 6",
                                                                      "Euro 6c",
                                                                      "Euro 6d",
                                                                      "Euro 6d-TEMP")),
                                selectInput("usage_type", "Usage Type", c("New", "Used")),
                                checkboxInput("adaptive_cruise_control", "Adaptive Cruise Control"),
                                checkboxInput("adaptive_headlights", "Adaptive Head Lights"),
                                checkboxInput("air_conditioning", "Air Conditioning"),
                                checkboxInput("Alarm System", "Alarm System"),
                                checkboxInput("alloy_wheels", "Allow Wheels"),
                                checkboxInput("armrest", "Arm Rest"),
                                checkboxInput("automatic_climate_control", "Automatic Climate Control"),
                                checkboxInput("auxiliary_heating", "Auxeliary Heating"),
                                checkboxInput("blind_spot_monitor", "Blind Spot Monitor"),
                                checkboxInput("bluetooth", "Bluetooth"),
                                checkboxInput("cab_or_rented", "Cab or rented"),
                                checkboxInput("catalytic_converter", "Catalytic Converter"),
                                checkboxInput("cd_player", "CD Player"),
                                checkboxInput("central_door_lock", "Central Door Lock"),
                                checkboxInput("cruise_control", "Cruise Control"),
                                checkboxInput("daytime_running_lights", "Daytime Running Lights"),
                                checkboxInput("digital_radio", "Digital Radio"),
                                checkboxInput("driver_drowsiness_detection", "Driver Drowsniess Detection"),
                                checkboxInput("driver_side_airbag", "Driver Side Airbag"),
                                checkboxInput("electric_tailgate", "Electric Tailgate"),
                                checkboxInput("electrical_sidemirrors", "Electrical Sidemirrors"),
                                checkboxInput("electrically_adjustable_seats", "Electrically Adjustable Seats"),
                                checkboxInput("electronic_stability_control", "Electronic Stability Control"),
                                checkboxInput("emergency_brake_assistant", "Emergency Brake Assistant"),
                                checkboxInput("emergency_system", "Emergency System"),
                                checkboxInput("fog_lights", "Fog Lights"),
                                checkboxInput("full_service", "Full Service"),
                                checkboxInput("handicapped_enabled", "Handicapped enabled"),
                                checkboxInput("hands_free_equipment", "Hands Free Equipment"),
                                checkboxInput("head_airbag", "Head Airbag"),
                                checkboxInput("heads_up_display", "Heads Up Display"),
                                checkboxInput("heated_steering_wheel", "Heated Steering Wheel"),
                                checkboxInput("hill_holder", "Hill Holder"),
                                checkboxInput("immobilizer", "Immobilizer"),
                                checkboxInput("inspection_new", "Inspection New"),
                                checkboxInput("isofix", "Isofix"),
                                checkboxInput("keyless_central_door_lock", "Keyless Central Door Lock"),
                                checkboxInput("lane_departure_warning_system", "Lane Departure Warning System"),
                                checkboxInput("leather_steering_wheel", "Leather Steering Wheel"),
                                checkboxInput("led_daytime_running_lights", "LED Daytime running Lights"),
                                checkboxInput("led_headlights", "LED Headlights"),
                                checkboxInput("light_sensor", "Light Sensor"),
                                checkboxInput("lumbar_support", "Lumbar Support"),
                                checkboxInput("massage_seats", "Massage Seats"),
                                checkboxInput("mp3", "MP3"),
                                checkboxInput("multi_function_steering_wheel", "Multi Function Steering Wheel"),
                                checkboxInput("navigation_system", "Navigation System"),
                                checkboxInput("night_view_assist", "Night View Assistant"),
                                
                                checkboxInput("non_smoking", "Non Smoking"),
                                checkboxInput("onboard_computer", "Onboard Computer"),
                                checkboxInput("panorama_roof", "Panorama Roof"),
                                checkboxInput("park_distance_control", "Park Distance Control"),
                                checkboxInput("parking_assist_system_camera", "Parking Assist System Camera"),
                                checkboxInput("parking_assist_system_self_steering", "Parking Assist System Self Steering"),
                                
                                checkboxInput("parking_assist_system_sensors_front", "Parking Assist System Sensors Front"),
                                checkboxInput("parking_assist_system_sensors_rear", "Parking Assist System Sensors Rear"),
                                checkboxInput("power_steering", "Power Steering"),
                                checkboxInput("power_windows", "Power Windows"),
                                checkboxInput("radio", "radio"),
                                checkboxInput("rain_sensor", "Rain Sensor"),
                                checkboxInput("rear_airbag", "Rear Airbag"),
                                checkboxInput("right_hand_drive", "Right Hand Drive"),
                                checkboxInput("roof_rack", "Roof Rack"),
                                checkboxInput("seat_heating", "Seat Heating"),
                                checkboxInput("seat_ventilation", "Seat Ventilation"),
                                checkboxInput("shift_paddle", "Shift Paddles"),
                                checkboxInput("side_airbag", "Side Airbag"),
                                checkboxInput("ski_bag", "Ski bag"),
                                checkboxInput("sliding_door", "Sliding Door"),
                                checkboxInput("sound_system", "Sound System"),
                                checkboxInput("split_rear_seats", "Split Rear Seats"),
                                checkboxInput("sport_package", "Sport Package"),
                                checkboxInput("sport_seats", "Sport Seats"),
                                checkboxInput("sport_suspension", "Sport Suspension"),
                                checkboxInput("start_stop_system", "Start Stop System"),
                                checkboxInput("sun_roof", "Sunroof"),
                                checkboxInput("television", "Television"),
                                checkboxInput("tinted_windows", "Tinted Windows"),
                                checkboxInput("tire_pressure_monitoring_system", "Tire Pressure Monitoring System"),
                                checkboxInput("touch_screen", "Touch Screen"),
                                checkboxInput("traction_control", "Traction Control"),
                                checkboxInput("traffic_sign_recognition", "Traffic Sign Recognition"),
                                checkboxInput("trailer_hitch", "Trailer Hitch"),
                                checkboxInput("tuned_car", "Tuned Car"),
                                checkboxInput("usb", "USB"),
                                checkboxInput("voice_control", "Voice Control"),
                                checkboxInput("warranty", "Warranty"),
                                checkboxInput("wd4", "WD4"),
                                checkboxInput("wind_deflector", "Wind Deflector"),
                                checkboxInput("winter_tyres", "Winter Tyres"),
                                checkboxInput("xenon_headlights", "Xenon Headlights"),
                                bookmarkButton(id="carBookmark")
                            ),
                            tabBox(width=8,
                                    tabPanel(
                                            title="CAR SOM 2D",
                                            plotlyOutput("carsomUmatrix2d"), DT::dataTableOutput("som_cars")),
                                   tabPanel(title="CAR SOM 3D",
                                            plotlyOutput("carsomUmatrix3d")),
                                   tabPanel(title="Details",
                                            DT::dataTableOutput("all_cars"))
                                ),
                        )
                    )
        ))
    ))
}
